import createDOMPurify from 'dompurify'

const ALLOWED_FONT_SIZES = new Set(['2', '3', '5'])
const purifier =
  typeof window === 'undefined'
    ? null
    : createDOMPurify(window)

if (purifier) {
  purifier.addHook(
    'uponSanitizeAttribute',
    (node, data) => {
      if (data.attrName !== 'size') {
        return
      }

      if (node.nodeName.toLowerCase() !== 'font') {
        data.keepAttr = false

        return
      }

      if (!ALLOWED_FONT_SIZES.has(data.attrValue)) {
        data.keepAttr = false
      }
    }
  )
}

export const NOTE_HTML_ALLOWED_TAGS = [
  'b',
  'strong',
  'i',
  'em',
  'font',
  'br',
  'div',
  'p',
]

export const NOTE_HTML_ALLOWED_ATTRIBUTES = {
  font: ['size'],
}

/**
 * Sanitizes rich text produced by the notes/reviews editor.
 *
 * The policy preserves only the formatting exposed by the current toolbar and
 * common browser line-break containers generated by contentEditable.
 *
 * @param {string} html - User-provided editor HTML.
 * @returns {string} Safe HTML for rendering or persistence.
 */
export function sanitizeNoteHtml(html) {
  const sourceHtml = String(html || '')

  if (!purifier) {
    return sourceHtml.replace(/<[^>]*>/g, '')
  }

  return purifier.sanitize(sourceHtml, {
    ALLOWED_TAGS: NOTE_HTML_ALLOWED_TAGS,
    ALLOWED_ATTR: ['size'],
    FORBID_ATTR: ['style'],
    FORBID_TAGS: [
      'a',
      'iframe',
      'img',
      'math',
      'object',
      'script',
      'svg',
      'template',
    ],
    KEEP_CONTENT: true,
  })
}
